# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scenario_pb2 as scenario__pb2


class SimulationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSimulation = channel.unary_stream(
                '/Simulation/RunSimulation',
                request_serializer=scenario__pb2.ID.SerializeToString,
                response_deserializer=scenario__pb2.Report.FromString,
                )
        self.StartScenario = channel.unary_unary(
                '/Simulation/StartScenario',
                request_serializer=scenario__pb2.ID.SerializeToString,
                response_deserializer=scenario__pb2.Confirmation.FromString,
                )


class SimulationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSimulation': grpc.unary_stream_rpc_method_handler(
                    servicer.RunSimulation,
                    request_deserializer=scenario__pb2.ID.FromString,
                    response_serializer=scenario__pb2.Report.SerializeToString,
            ),
            'StartScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScenario,
                    request_deserializer=scenario__pb2.ID.FromString,
                    response_serializer=scenario__pb2.Confirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Simulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Simulation/RunSimulation',
            scenario__pb2.ID.SerializeToString,
            scenario__pb2.Report.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulation/StartScenario',
            scenario__pb2.ID.SerializeToString,
            scenario__pb2.Confirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
